#region Namespace
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
//using Aspose.Cells.Charts;
using Autodesk.Revit.ApplicationServices;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using Autodesk.Revit.UI.Selection;
#endregion

namespace BIMScreeningOpgave
{
    [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Manual)]
    public class Class5 : IExternalCommand
    {


        public Autodesk.Revit.UI.Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            UIApplication uiapp = commandData.Application;
            UIDocument uidoc = uiapp.ActiveUIDocument;
            Application app = uiapp.Application;
            Document doc = uidoc.Document;

            FilteredElementCollector collector = new FilteredElementCollector(doc); // Collector
            ElementCategoryFilter filter = new ElementCategoryFilter(BuiltInCategory.OST_StructuralColumns); //Find all StructualColumns Elements
            IList<Element> StructuralColumns = collector.WherePasses(filter).WhereElementIsNotElementType().ToElements(); // Collect and store the StructuralColumn Elements in iList AllColumns
            foreach (Element ele in StructuralColumns) //Loop through the StructuralColumns iList
            {
                Parameter para = ele.LookupParameter("Top Offset"); // Set Parameter para too Top Offset, as we need to change the TopOffset 
                string storage = para.StorageType.ToString();  // Store as a string
                double value = para.AsDouble();
                double newvalue = UnitUtils.ConvertToInternalUnits(-480, UnitTypeId.Millimeters); // Transforms to mm so -480mm (.set only takes feet)

                using (Transaction t = new Transaction(doc, "Set parameter"))
                {
                    t.Start("param");
                    try
                    {
                        para.Set(newvalue);  // Set Top Offset field to value -480 
                    }
                    catch { };
                    t.Commit();
                }

            }

            return Result.Succeeded;
        }


    }
}
